// sveltekit-version/src/components/HomePageHeroImageSection/HomePageHeroImageSection.svelte
<script lang="ts">
	import bg from '$lib/images/home/1.jpg';
	import down_arrow from '$lib/images/down-arrow.png';
	let { children } = $props();
</script>

<section class="section">
	<div class="tall:h-[100vh] relative w-full items-center justify-between text-sm">
		<div
			class="before:bg-recipeHeroScrim flex h-full w-full items-center justify-center before:absolute before:z-10 before:block before:h-full before:w-full"
		>
			<img
				src={bg}
				alt="JustBeStillDesign"
				class="absolute h-full w-full object-cover"
			/>
			{@render children?.()}
			<div class="absolute bottom-0 z-10 mb-5 animate-bounce">
				<button>
					<img src={down_arrow} alt="Down Arrow" width={50} height={50} />
				</button>
			</div>
		</div>
	</div>
</section>

// components/HomePageHeroImageSection.tsx
import Image, { StaticImageData } from "next/image";
import React, { useCallback } from "react";
import down_icon from "@/public/down-arrow.png";

export default function HomePageHeroImageSection({
  children,
  src,
  alt,
}: {
  children: React.ReactNode;
  src: StaticImageData;
  alt: string;
}) {
  return (
    <section className="section">
      <div className="relative w-full tall:h-[100vh] items-center justify-between text-sm">
        <div className="flex justify-center items-center w-full h-full before:absolute before:block before:w-full before:h-full before:z-10 before:bg-recipeHeroScrim">
          <Image
            src={src}
            alt={alt}
            fill
            sizes="100vw"
            objectFit="cover"
            placeholder="blur"
          />
          {children}
          <div className="absolute bottom-0 mb-5 animate-bounce z-10">
            <button>
              <Image
                src={down_icon}
                alt="Scroll Down"
                sizes="100vw"
                width={50}
                height={50}
              />
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}
